const COLORS=['#7777ee','#fff66d','#69f56f','#ff8f92'];
const DARK=['#0000dd','#817600','#008018','#d00000'];
const worker=new Worker('worker.js');
const state={names:['集合 1','集合 2','集合 3','集合 4'],activeIndices:[0],counts:[0,0],union:0,stats:Array.from({length:4},()=>({unique:0,raw:0,duplicates:0})),selected:0,resultOffset:0,resultItems:[],requestId:0,style:'white',percent:true,lineWidth:2,fontSize:28,fontFamily:'Arial, sans-serif'};
const el=id=>document.getElementById(id);const grid=el('listGrid'),svg=el('vennSvg'),shadeLayer=el('shadeLayer'),shapeLayer=el('shapeLayer'),labelLayer=el('labelLayer');let toastTimer;
function toast(message){const t=el('toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1500)}
function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function previewText(text){if(text.length<12000)return text;let end=0,lines=0;while(end<text.length&&lines<40){if(text.charCodeAt(end)===10)lines++;end++}return text.slice(0,end).replace(/\r/g,'')+'\n…';}
function createCards(){grid.innerHTML='';for(let i=0;i<4;i++){const card=document.createElement('article');card.className='list-card';card.style.setProperty('--set-color',DARK[i]);card.innerHTML=`<div class="list-card-head"><input class="list-name" value="${esc(state.names[i])}" aria-label="集合 ${i+1} 名称"></div><textarea spellcheck="false" aria-label="集合 ${i+1} 数据"></textarea><div class="list-foot"><span class="list-stat" title="0 个唯一元素">0 个元素</span><button class="clear-one">清空</button></div>`;const input=card.querySelector('.list-name'),area=card.querySelector('textarea');input.addEventListener('input',()=>{state.names[i]=input.value||`集合 ${i+1}`;renderDiagram()});area.addEventListener('paste',event=>{const text=event.clipboardData?.getData('text/plain');if(text==null)return;event.preventDefault();area.value=previewText(text);processItems([{index:i,text}])});let timer;area.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>processItems([{index:i,text:area.value}]),220)});card.querySelector('.clear-one').addEventListener('click',()=>{area.value='';worker.postMessage({type:'clear',index:i})});grid.appendChild(card)}}
function processItems(items){worker.postMessage({type:'setData',items})}
function updateCards(){[...grid.children].forEach((card,i)=>{const value=state.stats[i].unique.toLocaleString(),stat=card.querySelector('.list-stat');stat.textContent=`${value} 个元素`;stat.title=`${value} 个唯一元素`})}
function compactName(bit){return state.names[state.activeIndices[bit]]}
function regionName(mask){const inside=[],outside=[];for(let bit=0;bit<state.activeIndices.length;bit++)(mask&(1<<bit)?inside:outside).push(compactName(bit));return outside.length?`${inside.join(' ∩ ')} 中独有的元素`:inside.join(' ∩ ')}
function makeSvg(tag,attrs={}){const node=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,value);return node}
const POS={1:[[500,500]],2:[[300,500],[700,500],[500,500]],3:[[300,320],[700,320],[500,320],[500,680],[375,525],[625,525],[500,455]],4:[[175,450],[350,238],[275,350],[650,238],[313,613],[500,343],[378,475],[825,450],[500,750],[688,613],[575,678],[725,350],[425,678],[623,475],[500,588]]};
function ovalPath(cx,cy,w,h){const hw=w/2,hh=h/2;return`M ${cx} ${cy-hh} C ${cx+hw} ${cy-hh} ${cx+hw} ${cy+hh} ${cx} ${cy+hh} C ${cx-hw} ${cy+hh} ${cx-hw} ${cy-hh} ${cx} ${cy-hh} Z`}
function geometry(n){if(n===1)return [{tag:'circle',cx:500,cy:500,r:230,name:[500,208]}];if(n===2)return [{tag:'circle',cx:350,cy:500,r:230,name:[300,208]},{tag:'circle',cx:650,cy:500,r:230,name:[700,208]}];if(n===3)return [{tag:'circle',cx:350,cy:370,r:230,name:[300,68]},{tag:'circle',cx:650,cy:370,r:230,name:[700,68]},{tag:'circle',cx:500,cy:630,r:230,name:[500,933]}];return [{tag:'path',d:ovalPath(332.5,537.5,450,705),transform:'rotate(-45 332.5 537.5)',name:[175,800]},{tag:'path',d:ovalPath(482.5,450,450,705),transform:'rotate(-45 482.5 450)',name:[300,100]},{tag:'path',d:ovalPath(517.5,450,450,705),transform:'rotate(45 517.5 450)',name:[700,100]},{tag:'path',d:ovalPath(667.5,537.5,450,705),transform:'rotate(45 667.5 537.5)',name:[825,800]}]}
function shapeAttrs(g,extra={}){const attrs={...extra};for(const key of ['cx','cy','r','d','transform'])if(g[key]!==undefined)attrs[key]=g[key];return attrs}
function renderIntensity(geos,n){const defs=makeSvg('defs');shadeLayer.appendChild(defs);geos.forEach((g,bit)=>{const clip=makeSvg('clipPath',{id:`set-clip-${bit}`,'clipPathUnits':'userSpaceOnUse'});clip.appendChild(makeSvg(g.tag,shapeAttrs(g,{fill:'#fff'})));defs.appendChild(clip)});for(let mask=1;mask<(1<<n);mask++){const value=state.counts[mask]||0,pct=state.union?value/state.union:0,gray=value?Math.max(0,255-Math.round(pct*255)):255;const regionMask=makeSvg('mask',{id:`region-mask-${mask}`,maskUnits:'userSpaceOnUse',x:0,y:0,width:1000,height:1000});regionMask.appendChild(makeSvg('rect',{x:0,y:0,width:1000,height:1000,fill:'#fff'}));for(let bit=0;bit<n;bit++)if(!(mask&(1<<bit)))regionMask.appendChild(makeSvg(geos[bit].tag,shapeAttrs(geos[bit],{fill:'#000'})));defs.appendChild(regionMask);let parent=shadeLayer;for(let bit=0;bit<n;bit++)if(mask&(1<<bit)){const clipped=makeSvg('g',{'clip-path':`url(#set-clip-${bit})`});parent.appendChild(clipped);parent=clipped}parent.appendChild(makeSvg('rect',{x:0,y:0,width:1000,height:1000,fill:`rgb(${gray},${gray},${gray})`,mask:`url(#region-mask-${mask})`}))}}
function renderDiagram(){shadeLayer.innerHTML='';shapeLayer.innerHTML='';labelLayer.innerHTML='';const n=state.activeIndices.length,geos=geometry(n);if(state.style==='intensity')renderIntensity(geos,n);geos.forEach((g,bit)=>{const actual=state.activeIndices[bit],fill=state.style==='color'?COLORS[actual]:state.style==='white'?'#fff':'none',shape=makeSvg(g.tag,shapeAttrs(g,{class:'set-shape',stroke:'#111','stroke-width':state.lineWidth,fill}));shape.setAttribute('fill-opacity',state.style==='color'?'.5':state.style==='white'?'.16':'0');shapeLayer.appendChild(shape);const name=makeSvg('text',{x:g.name[0],y:g.name[1],class:'set-name',fill:DARK[actual],'text-anchor':'middle','font-family':state.fontFamily});name.textContent=state.names[actual];shapeLayer.appendChild(name)});const positions=POS[n];for(let mask=1;mask<(1<<n);mask++){const [x,y]=positions[mask-1],value=state.counts[mask]||0,pct=state.union?value/state.union*100:0,gray=value?255-Math.round(pct/100*255):255,textColor=state.style==='intensity'&&gray<128?'#fff':'#000';const group=makeSvg('g',{class:'region'+(state.selected===mask?' selected':''),tabindex:'0',role:'button','aria-label':`${regionName(mask)}，${value} 项`,transform:`translate(${x} ${y})`});group.appendChild(makeSvg('circle',{class:'hit',cx:0,cy:0,r:36}));if(state.selected===mask)group.appendChild(makeSvg('rect',{x:-46,y:state.percent?-36:-25,width:92,height:state.percent?66:48,fill:'none',stroke:textColor,'stroke-width':1}));const count=makeSvg('text',{x:0,y:state.percent?-3:7,class:'count',fill:textColor,'font-family':state.fontFamily,'font-size':state.fontSize});count.textContent=value.toLocaleString();group.appendChild(count);if(state.percent){const percent=makeSvg('text',{x:0,y:20,class:'percent',fill:textColor,'font-family':state.fontFamily});percent.textContent=`(${pct<.1&&pct>0?'<0.1':pct.toFixed(pct>=10?1:2)}%)`;group.appendChild(percent)}group.addEventListener('click',event=>{event.stopPropagation();selectRegion(mask)});group.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectRegion(mask)}});labelLayer.appendChild(group)}}
function resetResults(){state.selected=0;state.resultOffset=0;state.resultItems=[];el('resultList').innerHTML='';el('loadMore').hidden=true;el('downloadRegion').disabled=true}
function clearSelection(){if(!state.selected)return;resetResults();renderDiagram()}
function selectRegion(mask){state.selected=mask;state.resultOffset=0;state.resultItems=[];el('resultList').innerHTML=`<div class="result-title">${esc(regionName(mask))}：${(state.counts[mask]||0).toLocaleString()} 项</div>`;el('downloadRegion').disabled=!(state.counts[mask]>0);fetchRegion();renderDiagram()}
function fetchRegion(){if(!state.selected)return;state.requestId++;worker.postMessage({type:'region',mask:state.selected,offset:state.resultOffset,limit:500,requestId:state.requestId})}
function showRegionPage(items){state.resultItems.push(...items);const frag=document.createDocumentFragment();items.forEach(value=>{const row=document.createElement('div');row.className='result-item';row.textContent=value;frag.appendChild(row)});el('resultList').appendChild(frag);state.resultOffset+=items.length;el('loadMore').hidden=state.resultOffset>=(state.counts[state.selected]||0)||items.length===0}
function updateSummary(message){state.counts=message.counts;state.union=message.union;state.stats=message.stats;state.activeIndices=message.activeIndices?.length?message.activeIndices:[0];updateCards();resetResults();renderDiagram()}
worker.onmessage=event=>{const message=event.data;if(message.type==='summary')updateSummary(message);else if(message.type==='region'&&message.requestId===state.requestId)showRegionPage(message.items)};worker.onerror=()=>toast('计算失败，请重新输入');
el('loadExample').onclick=event=>{event.preventDefault();const samples=[['apple','banana','orange','grape'],['banana','grape','pear','kiwi'],[],[]],areas=[...grid.querySelectorAll('textarea')],updates=[];samples.forEach((items,index)=>{const text=items.join('\n');areas[index].value=text;updates.push({index,text})});processItems(updates)};
el('upperCase').onclick=()=>{worker.postMessage({type:'transform',mode:'upper'});[...grid.querySelectorAll('textarea')].forEach(area=>{if(!area.value.endsWith('\n…'))area.value=area.value.toUpperCase()})};el('lowerCase').onclick=()=>{worker.postMessage({type:'transform',mode:'lower'});[...grid.querySelectorAll('textarea')].forEach(area=>{if(!area.value.endsWith('\n…'))area.value=area.value.toLowerCase()})};el('loadMore').onclick=fetchRegion;
el('styleMode').onchange=event=>{state.style=event.target.value;renderDiagram()};el('showPercent').onchange=event=>{state.percent=event.target.checked;renderDiagram()};el('lineWidth').onchange=event=>{state.lineWidth=Math.max(1,Math.min(8,Number(event.target.value)||2));event.target.value=state.lineWidth;renderDiagram()};el('fontSize').onchange=event=>{state.fontSize=Math.max(12,Math.min(36,Number(event.target.value)||22));event.target.value=state.fontSize;renderDiagram()};el('fontFamily').onchange=event=>{state.fontFamily=event.target.value;renderDiagram()};document.querySelectorAll('.step').forEach(button=>button.onclick=()=>{const input=el(button.dataset.for),next=Number(input.value)+Number(button.dataset.step);input.value=Math.max(Number(input.min),Math.min(Number(input.max),next));input.dispatchEvent(new Event('change'))});
function exportSvgText(){const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width','1280');clone.setAttribute('height','1280');clone.querySelectorAll('.hit,.region > rect').forEach(node=>node.remove());clone.querySelectorAll('.set-name').forEach(node=>{node.setAttribute('font-family','Arial, sans-serif');node.setAttribute('font-size',String(state.fontSize));node.setAttribute('font-weight','400')});clone.querySelectorAll('.count').forEach(node=>{node.setAttribute('text-anchor','middle');node.setAttribute('font-family','Arial, sans-serif');node.setAttribute('font-size',String(state.fontSize));node.setAttribute('font-weight','700')});clone.querySelectorAll('.percent').forEach(node=>{node.setAttribute('text-anchor','middle');node.setAttribute('font-family','Arial, sans-serif');node.setAttribute('font-weight','600');node.setAttribute('font-size',String(Math.max(16,Math.round(state.fontSize*.68))));node.setAttribute('y','28')});return new XMLSerializer().serializeToString(clone)}
function download(blob,name){const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function exportSvg(){download(new Blob([exportSvgText()],{type:'image/svg+xml'}),'vennflow.svg');toast('SVG 已导出')}
function exportPng(){const image=new Image(),url=URL.createObjectURL(new Blob([exportSvgText()],{type:'image/svg+xml;charset=utf-8'}));image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=1280;const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,1280,1280);context.drawImage(image,0,0,1280,1280);URL.revokeObjectURL(url);canvas.toBlob(blob=>{if(blob)download(blob,'vennflow.png');toast(blob?'PNG 已导出':'PNG 导出失败')},'image/png')};image.onerror=()=>{URL.revokeObjectURL(url);toast('PNG 导出失败')};image.src=url}
el('exportSvg').onclick=exportSvg;el('exportPng').onclick=exportPng;el('exportCsv').onclick=()=>{const rows=['区域,数量,占比'];for(let mask=1;mask<(1<<state.activeIndices.length);mask++){const pct=state.union?(state.counts[mask]/state.union*100).toFixed(4):'0';rows.push(`"${regionName(mask).replace(/"/g,'""')}",${state.counts[mask]||0},${pct}%`)}download(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}),'vennflow-statistics.csv')};
el('figureWrap').addEventListener('contextmenu',event=>{event.preventDefault();const menu=el('contextMenu');menu.hidden=false;menu.style.left=`${Math.min(event.clientX,innerWidth-155)}px`;menu.style.top=`${Math.min(event.clientY,innerHeight-90)}px`});document.addEventListener('click',event=>{if(!event.target.closest('#contextMenu'))el('contextMenu').hidden=true});el('contextMenu').onclick=event=>{const type=event.target.dataset.export;if(type==='png')exportPng();if(type==='svg')exportSvg();el('contextMenu').hidden=true};
svg.addEventListener('click',event=>{if(!event.target.closest('.region'))clearSelection()});
el('downloadRegion').onclick=()=>{const total=state.counts[state.selected]||0;if(total>state.resultItems.length){const gather=()=>{if(state.resultItems.length>=total){download(new Blob([state.resultItems.join('\n')],{type:'text/plain;charset=utf-8'}),'vennflow-region.txt');return}const requestId=`download-${Date.now()}-${state.resultItems.length}`,handler=event=>{if(event.data.type==='region'&&event.data.requestId===requestId){worker.removeEventListener('message',handler);state.resultItems.push(...event.data.items);if(event.data.items.length)gather()}};worker.addEventListener('message',handler);worker.postMessage({type:'region',mask:state.selected,offset:state.resultItems.length,limit:10000,requestId})};gather()}else download(new Blob([state.resultItems.join('\n')],{type:'text/plain;charset=utf-8'}),'vennflow-region.txt')};
function registerWebMCP(){const context=document.modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{void Promise.resolve(context.registerTool({name:'set_venn_data',title:'设置韦恩图数据',description:'一次设置最多四组列表，并按非空列表自动生成韦恩图。',inputSchema:{type:'object',properties:{lists:{type:'array',minItems:1,maxItems:4,items:{type:'object',properties:{name:{type:'string'},items:{type:'array',items:{type:'string'}}},required:['name','items'],additionalProperties:false}}},required:['lists'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!Array.isArray(input?.lists)||!input.lists.length||input.lists.length>4)throw new Error('需要 1–4 组列表');const items=[];input.lists.forEach((list,index)=>{state.names[index]=String(list.name||`集合 ${index+1}`);items.push({index,text:list.items.join('\n')})});createCards();processItems(items);return{updated:true,listCount:input.lists.length}}},{signal:controller.signal})).catch(()=>{})}catch{}}
function registerAutoVennTool(){
  const context=document.modelContext;
  if(!context?.registerTool)return;
  const controller=new AbortController();
  const tool={
    name:'set_venn_data_auto',title:'自动设置韦恩图数据',
    description:'设置最多四组列表，空列表不会出现在图中。',
    inputSchema:{type:'object',properties:{lists:{type:'array',minItems:1,maxItems:4,items:{type:'object',properties:{name:{type:'string'},items:{type:'array',items:{type:'string'}}},required:['name','items'],additionalProperties:false}}},required:['lists'],additionalProperties:false},
    annotations:{readOnlyHint:false,untrustedContentHint:false},
    async execute(input){
      if(!Array.isArray(input?.lists)||!input.lists.length||input.lists.length>4)throw new Error('需要 1–4 组列表');
      const areas=[...grid.querySelectorAll('textarea')],nameInputs=[...grid.querySelectorAll('.list-name')],updates=[];
      for(let index=0;index<4;index++){
        const list=input.lists[index]||{name:`集合 ${index+1}`,items:[]};
        state.names[index]=String(list.name||`集合 ${index+1}`);nameInputs[index].value=state.names[index];
        const text=Array.isArray(list.items)?list.items.map(String).join('\n'):'';areas[index].value=previewText(text);updates.push({index,text});
      }
      processItems(updates);return{updated:true,nonEmptyLists:input.lists.filter(list=>list.items?.length).length};
    }
  };
  try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}
}
createCards();renderDiagram();registerAutoVennTool();
