let sets=[new Set(),new Set(),new Set(),new Set()];
let rawCounts=[0,0,0,0];
let duplicateCounts=[0,0,0,0];
let activeIndices=[0];

function parseLines(text){const output=new Set();let lines=0,start=0;for(let index=0;index<=text.length;index++){if(index===text.length||text.charCodeAt(index)===10){let value=text.slice(start,index);if(value.endsWith('\r'))value=value.slice(0,-1);value=value.trim();if(value){lines++;output.add(value)}start=index+1}}return{set:output,lines,duplicates:lines-output.size}}
function refreshActive(){activeIndices=[];for(let index=0;index<sets.length;index++)if(sets[index].size)activeIndices.push(index);if(!activeIndices.length)activeIndices=[0]}
function maskFor(value){let mask=0;for(let bit=0;bit<activeIndices.length;bit++)if(sets[activeIndices[bit]].has(value))mask|=1<<bit;return mask}
function summarize(){refreshActive();const counts=new Array(1<<activeIndices.length).fill(0);for(let bit=0;bit<activeIndices.length;bit++){const sourceIndex=activeIndices[bit],sourceBit=1<<bit;for(const value of sets[sourceIndex]){const mask=maskFor(value);if((mask&-mask)===sourceBit)counts[mask]++}}const union=counts.reduce((sum,value)=>sum+value,0);postMessage({type:'summary',counts,union,activeIndices,stats:sets.map((set,index)=>({unique:set.size,raw:rawCounts[index],duplicates:duplicateCounts[index]}))})}
self.onmessage=event=>{const message=event.data;if(message.type==='setData'){for(const item of message.items){const parsed=parseLines(String(item.text||''));sets[item.index]=parsed.set;rawCounts[item.index]=parsed.lines;duplicateCounts[item.index]=parsed.duplicates}summarize()}else if(message.type==='clear'){sets[message.index]=new Set();rawCounts[message.index]=0;duplicateCounts[message.index]=0;summarize()}else if(message.type==='transform'){for(let index=0;index<4;index++){const next=new Set();for(const value of sets[index])next.add(message.mode==='upper'?value.toUpperCase():value.toLowerCase());sets[index]=next;duplicateCounts[index]=Math.max(0,rawCounts[index]-next.size)}summarize()}else if(message.type==='region'){const mask=Number(message.mask),offset=Math.max(0,Number(message.offset)||0),limit=Math.min(10000,Math.max(1,Number(message.limit)||500)),included=[];for(let bit=0;bit<activeIndices.length;bit++)if(mask&(1<<bit))included.push(activeIndices[bit]);const source=included.reduce((best,index)=>sets[index].size<sets[best].size?index:best,included[0]),items=[];let seen=0;if(source!==undefined){for(const value of sets[source]){if(maskFor(value)!==mask)continue;if(seen++<offset)continue;items.push(value);if(items.length>=limit)break}}postMessage({type:'region',items,requestId:message.requestId})}};
